#!/bin/sh
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2001.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2001.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2003.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2003.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2020.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2020.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2008.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2008.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2009.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2009.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2002.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2002.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2000.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2000.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_1999.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_1999.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2002.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2002.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2009.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2009.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2000.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2000.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2001.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2001.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2008.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2008.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2020.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2020.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2003.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2003.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_1998.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_1998.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2007.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2007.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2018.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2018.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_1997.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_1997.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2005.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2005.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/.DS_Store --output emb/.DS_S.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2004.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2004.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_1996.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_1996.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2019.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2019.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2006.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2006.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2004.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2004.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_1994.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_1994.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2006.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2006.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2019.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2019.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2018.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2018.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2007.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2007.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_1995.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_1995.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2005.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2005.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2009.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2009.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_1999.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_1999.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2002.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2002.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2003.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2003.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_1998.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_1998.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2008.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2008.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2020.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2020.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2001.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2001.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_1998.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_1998.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_1999.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_1999.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2000.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2000.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_1994.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_1994.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2004.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2004.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_1996.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_1996.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_1997.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_1997.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2005.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2005.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_1995.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_1995.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2018.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2018.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_1997.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_1997.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2007.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2007.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_1995.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_1995.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_1994.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_1994.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2006.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2006.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_1996.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_1996.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2019.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2019.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2000.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2000.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_1999.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_1999.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_1998.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_1998.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2001.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2001.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2003.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2003.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_1998.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_1998.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2008.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2008.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2020.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2020.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2009.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2009.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_1999.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_1999.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2002.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2002.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2006.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2006.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_1996.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_1996.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2019.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2019.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_1994.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_1994.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_1995.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_1995.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2018.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_2018.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_1997.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_1997.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2007.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2007.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2005.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2005.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_1995.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_1995.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_1997.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_1997.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_1996.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_1996.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_1994.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_1994.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2004.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_2004.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2008.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2008.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2020.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2020.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2003.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2003.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_1998.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_1998.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2001.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2001.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2000.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2000.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_1_year_1999.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_1_year_1999.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2002.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2002.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2009.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2009.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2000.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2000.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2009.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2009.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2002.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2002.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2003.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2003.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2020.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2020.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2008.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2008.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2001.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2001.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_1995.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_1995.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2005.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2005.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2018.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2018.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2007.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2007.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2006.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2006.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2019.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_1_year_2019.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2004.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2004.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_1994.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_1994.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_1996.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_1996.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2019.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2019.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2006.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2006.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2004.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2004.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2005.edg --output emb/SemanticGraph_delta_3_cutoff_0_minedge_3_year_2005.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2007.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_3_year_2007.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2018.edg --output emb/SemanticGraph_delta_3_cutoff_25_minedge_1_year_2018.emb --verbose --mode SparseOTF --p 2 --epochs 2
pecanpy --input edg/SemanticGraph_delta_3_cutoff_5_minedge_3_year_1997.edg --output emb/SemanticGraph_delta_3_cutoff_5_minedge_3_year_1997.emb --verbose --mode SparseOTF --p 2 --epochs 2
